{
    "metadata": {
        "kernelspec": {
            "name": "SQL",
            "display_name": "SQL",
            "language": "sql"
        },
        "language_info": {
            "name": "sql",
            "version": ""
        }
    },
    "nbformat_minor": 2,
    "nbformat": 4,
    "cells": [
        {
            "cell_type": "markdown",
            "source": [
                "to get all records from the table"
            ],
            "metadata": {
                "azdata_cell_guid": "d00f6199-b31a-4e63-b973-e0c42bdd828e"
            }
        },
        {
            "cell_type": "code",
            "source": [
                "SELECT * FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the Total Revenue\n",
                "SELECT CAST(SUM([total_price]) AS DECIMAL(10,2)) AS Total_Revenue FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the average order value \n",
                "SELECT CAST(CAST(SUM([total_price]) AS DECIMAL(10,2)) / CAST(COUNT(DISTINCT [order_id]) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS Avg_Order_Value FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the total pizzas sold \n",
                "SELECT SUM([quantity]) AS Total_Pizza_Sold FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the total orders \n",
                "SELECT COUNT(DISTINCT [order_id]) AS Total_Orders FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the average pizzas per order\n",
                "SELECT CAST(CAST(SUM([quantity]) AS DECIMAL(10,2)) / CAST(COUNT(DISTINCT [order_id]) AS DECIMAL(10,2)) AS DECIMAL(10,2)) AS Avg_Pizza_Per_Order FROM [dbo].[Pizza_Sales]\n",
                "\n",
                "--to get the daily trend for total orders\n",
                "SELECT DATENAME(DW, [order_date]) AS Order_day, COUNT(DISTINCT [order_id]) AS Total_Orders\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY DATENAME(DW, [order_date])\n",
                "\n",
                "--to get the monthly trend for total orders\n",
                "SELECT DATENAME(MONTH, [order_date]) AS Month_Name, COUNT(DISTINCT [order_id]) AS Total_Orders\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY DATENAME(MONTH, [order_date])\n",
                "ORDER BY Total_Orders DESC\n",
                "\n",
                "--to get percentage of sales by pizza category\n",
                "SELECT [pizza_category], SUM([total_price]) AS Total_Sales, SUM([total_price]) * 100 / (SELECT SUM([total_price]) FROM [dbo].[Pizza_Sales]) AS PCT_Total_Sales\n",
                "FROM [dbo].[Pizza_Sales] \n",
                "GROUP BY [pizza_category]\n",
                "\n",
                "--to get percentage of sales by pizza category when applying filter \n",
                "SELECT [pizza_category], SUM([total_price]) AS Total_Sales, SUM([total_price]) * 100 / \n",
                "(SELECT SUM([total_price]) FROM [dbo].[Pizza_Sales] WHERE MONTH([order_date]) = 1) AS PCT_Total_Sales\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "WHERE MONTH([order_date]) = 1\n",
                "GROUP BY [pizza_category]\n",
                "\n",
                "--to get percentage of sales by pizza size\n",
                "SELECT [pizza_size], CAST(SUM([total_price])AS DECIMAL(10,2)) AS Total_Revenue, CAST(SUM([total_price]) * 100 / (SELECT SUM([total_price]) FROM [dbo].[Pizza_Sales]) AS DECIMAL(10,2)) AS PCT\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_size]\n",
                "ORDER BY [pizza_size]\n",
                "\n",
                "--to get total pizzas sold by pizza category\n",
                "SELECT [pizza_category], SUM([quantity]) AS Total_Quantity_Sold\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_category]\n",
                "ORDER BY Total_Quantity_Sold DESC\n",
                "\n",
                "--to get Top 5 Best Sellers by Revenue, Total Quality and Total Orders\n",
                "--By Revenue\n",
                "SELECT TOP 5 [pizza_name], SUM([total_price]) AS Total_Revenue\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Revenue DESC\n",
                "\n",
                "--By Quantity\n",
                "SELECT TOP 5 [pizza_name], SUM([quantity]) AS Total_Pizza_Sold\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Pizza_Sold DESC\n",
                "\n",
                "--By Total Orders\n",
                "SELECT TOP 5 [pizza_name], COUNT(DISTINCT [order_id]) AS Total_Orders\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Orders DESC\n",
                "\n",
                "\n",
                "--To get Bottom 5 worst sellers by Revenue, Total Quality and Total Orders\n",
                "--By Revenue\n",
                "SELECT TOP 5 [pizza_name], SUM([total_price]) AS Total_Revenue\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Revenue ASC\n",
                "\n",
                "--By Quantity\n",
                "SELECT TOP 5 [pizza_name], SUM([quantity]) AS Total_Pizza_Sold\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Pizza_Sold ASC\n",
                "\n",
                "--By Total Orders\n",
                "SELECT TOP 5 [pizza_name], COUNT(DISTINCT [order_id]) AS Total_Orders\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Orders ASC\n",
                "\n",
                "--note to take when filtering \n",
                "--If you want to apply the pizza_category or pizza_size filters to the above queries you can use WHERE clause. Follow some of below examples\n",
                "\n",
                "SELECT TOP 5 [pizza_name], COUNT(DISTINCT [order_id]) AS Total_Orders\n",
                "FROM [dbo].[Pizza_Sales]\n",
                "WHERE [pizza_category] = 'Classic'\n",
                "GROUP BY [pizza_name]\n",
                "ORDER BY Total_Orders ASC"
            ],
            "metadata": {
                "azdata_cell_guid": "25f7c6d9-9ccc-4e7e-843e-8f43ec176046",
                "language": "sql"
            },
            "outputs": [],
            "execution_count": null
        }
    ]
}